services:
  api:
    build: ./api
    container_name: fastapi-ml
    environment:
    - OLLAMA_HOST=http://host.docker.internal:11434
    ports:
    - 8000:8000
    restart: unless-stopped
  grafana:
    container_name: grafana
    depends_on:
    - prometheus
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - grafana_data:/var/lib/grafana
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=7d
    container_name: prometheus
    depends_on:
    - api
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_data:/prometheus

volumes:
  grafana_data: null
  prometheus_data: null
